### ISSUE TITLE
enhancement : http/2 in place of http/1

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#10]
Hello, 
to reduce latency and saving header bandwitch, is it a good idea to implement http2 for chunk-server and client ? 

Regards, 
Nicolas

**Comment by folbricht** [comment]
The Go HTTP libraries do support HTTP/2 by default, but only when TLS is used. Similar to browsers. Might be able to enable HTTP/2 without TLS.

**Comment by folbricht** [comment]
There's apparently nothing in the standard library to enable h2c (HTTP/2 over non-TLS). Could perhaps use https://github.com/hkwi/h2c if we really wanted it.

**Comment by folbricht** [comment]
Rather that implement h2c from scratch to support HTTP/2, I added HTTPS chunk stores support which by default uses HTTP/2. There's now also a `-i` option to disable cert checks and allow you to use self-signed certs.

Server:
```
desync chunk-server -s /some/store -l :8443 -key key.pem -cert cert.pem
```

Client:
```
desync extract -s https://localhost:8443/ -i some.caibx /tmp/blob
```
