### ISSUE TITLE
Enhancement : add a "in-flight" request queue to desync chunk-server

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#103]
Hello,
 requests to desync chunk-server for the same chunk are made at the exact same time, and that chunk doesn't yet exist in the local cache then all requests will be sent to the upstream chunk server. Once of of these is successful the chunk will be in the cache and further requests will be served from it. 
There's currently no queue of "in-flight" requests kept in memory, add a these queue as 
 is that one of the requests is sent upstream, while the other 49 wait until the first one is done

Regards, 
Nicolas

**Comment by folbricht** [comment]
I believe this is only really useful to have on the `chunk-server` command since that's when multiple clients would be making a request for the same chunk concurrently. Most of the other desync commands are de-duping their chunk requests internally.

**Comment by limbo127** [comment]
Yes i’m agree
Regard
Nicolas

Le sam. 4 mai 2019 à 19:43, Frank Olbricht <notifications@github.com> a
écrit :

**Comment by folbricht** [comment]
This has been implemented on the issue-103 branch for HTTP servers. It'll now dedup concurrent requests.

@limbo127 It's very hard for me to test this as it requires a very large deployment. Would you be able to confirm this works as expected in your environment. Note that https://github.com/folbricht/desync/tree/issue-103 includes the changes from #101 as well, so this may be the one you want to build.

**Comment by limbo127** [comment]
thank,
I'm testing all this dev and I tell you if all is ok, thanks again, very
important for our deployment.
Nicolas

Le dim. 5 mai 2019 à 19:06, Frank Olbricht <notifications@github.com> a
écrit :
