### ISSUE TITLE
Add trailing slash in http store broken

### ISSUE THREAD

**Issue by jkirkwood** [folbricht/desync#112]
The add trailing slash functionality in `remotehttp.go` appears to be broken as shown here:
```go
// Make sure we have a trailing / on the path
u := *location
if !strings.HasSuffix(u.Path, "/") {
	u.Path = u.Path + "/"
}
```
`u := *location` makes a copy of the struct pointed to by `*location` ([see this StackOverflow](https://stackoverflow.com/questions/38443348/is-dereference-golang-struct-return-new-copy-of-struct)). The copy gets a `/` appended, but the original url struct pointed to by `location`, which is used to initialize the `RemoteHTTPBase`, remains unchanged.

This is causing problems specifically in the following command:
```
desync extract -s "http://localhost:3002/desync/store" "http://localhost:3002/desync/app.caibx" app.img
```
Where the request for `http://localhost:3002/desync/app.caibx` ends up being sent to `http://localhost:3002/app.caibx` instead.

Can we either add the slash to `location` directly, or change this:
```go
return &RemoteHTTPBase{location: location, client: client, opt: opt}, nil
```
to this:
```go
return &RemoteHTTPBase{location: &u, client: client, opt: opt}, nil
```

**Comment by folbricht** [comment]
Thanks for bringing this up. It's quite an old bug, but should be squashed now.
