### ISSUE TITLE
Unable to use mount-index be used to expose a caidx to qemu

### ISSUE THREAD

**Issue by SebastienAuvray** [folbricht/desync#12]
Hello,

After mounting a caidx file using desync mount-index, i try to use the blob as a device for qemu.
I tried using `sudo qemu-nbd -c /dev/nbd0  <blob_file>`, but keep getting the error :
`Failed to blk_new_open <blob_file>: Could not open <blob_file> : Permission denied`
Maybe I'm using it the wrong way. 

Thanx,

Sebastien.

**Comment by charles-dyfis-net** [comment]
mount-index works with caibx files only (single blobs), not caidx; it does not support catar format decoding at this time. (That's what distinguishes it from a future, not-yet-written `mount` command).

**Comment by SebastienAuvray** [comment]
OK, I got it.
Thanx !

Sebastien.
