### ISSUE TITLE
Update store config of long-running processes

### ISSUE THREAD

**Issue by folbricht** [folbricht/desync#122]
### Problem

Currently, long-running processes, namely `mount-index` and `chunk-server` need to be restarted to change their upstream store setup. In order to maintain 100% uptime, it'd be be good to be able to update the upstream chunk store config without restart, ideally under load.

### Possible solution

In addition to `-s` and `-c` options, support reading the store setup from a file with a new option like `--store-file <JSON file>`. Both, `chunk-server` and `mount-index` could handle SIGHUP, reload the file and replace the current store setup in the process.

### Example
- Start the process with desync chunk-server --store-file mystores.json .... Here instead of providing multiple -s/-c options in the command line, the upstream store config is read from a file
- Someone could edit the file
- kill -1 <PID> to make the process reload the store setup from the same file and update while being under load without downtime

**Comment by folbricht** [comment]
This has been implemented on the issue-122 branch. https://github.com/folbricht/desync/tree/issue-122#dynamic-store-configuration explains how to use it. Basically one creates a file like this:

```json
{
  "stores": [
    "/path/to/store1",
    "/path/to/store2"
  ],
  "cache": "/path/to/cache"
}
```
And then start the `chunk-server` or `mount-index` command with the new `--store-file` option. Then a SIGHUP will trigger a reload without restart, even under load.

**Comment by limbo127** [comment]
At this time #122 , mount-index seems to be dead lock ( fuse perhaps) when store chunk is down during an operation ( cat) , then store-file change and kill -HUP 1 , mount-index never comes back again. 
Nicolas

**Comment by folbricht** [comment]
With the update to the newer v2 API as per https://github.com/folbricht/desync/pull/130, I'm not seeing any lockups of the mount-index command.

**Comment by limbo127** [comment]
Hello, 
I can confirm that newer v2 APi correct this issue
thanks
