### ISSUE TITLE
Add mtree feature

### ISSUE THREAD

**Issue by BDZenix** [folbricht/desync#123]
I used to use casync to distribute files，and depend on it's mtree feature. Can desync also implement this feature? Thus I can totally replace casync with desync. Thanks

**Comment by folbricht** [comment]
That should be doable, especially since filesystem abstraction was implemented recently. Do you use it on archives/indexes only or also on directories? Which hash algorithm do you think it should support?

It won't match the output of casync exactly, since desync doesn't store things like the user/group names, only the IDs.

**Comment by BDZenix** [comment]
I tried to execute mtree command on caidx file generated by desync, and got the same result as casync except for user/group names. As I just use no-same-owner mode, user/group names field is not useful for me. I developed a version control tool with desync as the file distribution solution, which ignores the directory changes, just like git.  Considering backward compatibility, I hope you may keep other fields on casync unchanged.

**Comment by folbricht** [comment]
I'll definitely not be removing any fields from catar. In fact, I could be persuaded to add user/group fields if there's a use-case for it. Should be easy, but I haven't seen the need so far.

Currently working on an mtree subcommand, should have something shortly.

**Comment by folbricht** [comment]
@BDZenix That's been implemented on https://github.com/folbricht/desync/tree/issue-123 if you want to give that a try before I merge it to master.

`desync mtree archive.catar` or `desync mtree -s <store> -i archive.caidx`

**Comment by BDZenix** [comment]
> @BDZenix That's been implemented on https://github.com/folbricht/desync/tree/issue-123 if you want to give that a try before I merge it to master.
> 
> `desync mtree archive.catar` or `desync mtree -s <store> -i archive.caidx`

I checked it and find a format bug on `time` field, and a typo error `side`(size)：
![image](https://user-images.githubusercontent.com/16330887/64944512-15e25700-d8a1-11e9-811e-c96a492dc759.png)
![image](https://user-images.githubusercontent.com/16330887/64944560-327e8f00-d8a1-11e9-87fb-f95aa67a3f02.png)
![image](https://user-images.githubusercontent.com/16330887/64944779-b59fe500-d8a1-11e9-99e4-37d194453e60.png)

**Comment by folbricht** [comment]
Thanks a lot for taking a look and reporting back. Apparently I didn't look too closely at the output myself initially. The typo's been fixed now and the nanosecond part of the timestamp should now print with leading zeroes (total 9 as per spec).

**Comment by BDZenix** [comment]
I have another need, you may know casync does not serialize time info into chunk when '--with=sec-time' flag does not be set, which leads to less delta between two versions of publishments, especially when there are too many small files. Could you please support this feature on desync?

**Comment by charles-dyfis-net** [comment]
Incidentally, speaking as a user -- another way to achieve this goal of minimizing deltas is to have all timestamps set to a constant value (UNIX epoch-time `1` is used by the Nix build system / package manager, f/e).

**Comment by folbricht** [comment]
Moved the timestamp discussion to https://github.com/folbricht/desync/issues/124 and opened a PR for the mtree command in https://github.com/folbricht/desync/pull/125
