### ISSUE TITLE
Option to not serialize timestamps during tar

### ISSUE THREAD

**Issue by folbricht** [folbricht/desync#124]
As per https://github.com/folbricht/desync/issues/123#issuecomment-532630807, there should be a way to avoid including timestamps in archives to minimize the difference between similar archives.

Questions:
- Should this be the default operation?
- Does casync set the timestamp in the archive to 0 or leave out the timestamp record completely?

**Comment by BDZenix** [comment]
I think it's should be the default operation, for the most scene, people don't neet the origin timestamp, and modify mtime also leads to redunant syscall.

**Comment by folbricht** [comment]
From what I'm seeing, casync by default adds the timestamp to archives. It has to be disabled with something like `--without=all`. Thinking of adding a `--no-time` option to desync.

**Comment by charles-dyfis-net** [comment]
> I think it's should be the default operation, for the most scene, people don't neet the origin timestamp, and modify mtime also leads to redunant syscall.

I'd disagree on making this default -- "people don't need the origin timestamp" isn't always true. Some folks run automated integrity-checking tools that treat mtimes among the data they sign and later verify. Some folks have `Makefile`-style tools that decide what needs to be rebuilt by comparing timestamps. And when you have a distro with hundreds of packages from various authors, it only takes breaking *one* tool that assumes that timestamps will be retained to give someone a bad day (particularly when they don't have a reasonable expectation that their archiver will be throwing away that metadata).

I say the above as someone who *doesn't* ship timestamps in archives (or, rather, has them all set to 1 second past epoch). I'm not advocating for myself, but for consistent behavior with what UNIX admins have been trained to expect from archival tools for decades.

**Comment by folbricht** [comment]
@BDZenix I added a new `--no-time` option to the tar command on the issue-124 branch (https://github.com/folbricht/desync/tree/issue-124) if you'd like to try that out. It zeroes the timestamps in the archive, and during untar, zero timestamps are ignored (which means files will have a current timestamp).

**Comment by BDZenix** [comment]
> @BDZenix I added a new `--no-time` option to the tar command on the issue-124 branch (https://github.com/folbricht/desync/tree/issue-124) if you'd like to try that out. It zeroes the timestamps in the archive, and during untar, zero timestamps are ignored (which means files will have a current timestamp).

Good job!
