### ISSUE TITLE
The program cannot exit normally when an error occurs in UnTar function

### ISSUE THREAD

**Issue by BDZenix** [folbricht/desync#126]
look at: https://github.com/folbricht/desync/blob/master/untar.go#L114
when when an error occurs in UnTar function, this goroutine will block and the program cannot quit, even ctrl + c

**Comment by BDZenix** [comment]
to fix this bug:
`case req <- requestJob{chunk: c, data: data}: // request the chunk
				select {
				case <-ctx.Done():
					break loop
				case assemble <- data: // and hand over the data channel to the assembler
				}`

**Comment by BDZenix** [comment]
`case req <- requestJob{chunk: c, data: data}: // request the chunk
				select {
				case <-ctx.Done():
					break loop
				case assemble <- data: // and hand over the data channel to the assembler
				}
`

**Comment by BDZenix** [comment]
Since I have no permission to push, just attach the code that resolve this problem:
![image](https://user-images.githubusercontent.com/16330887/65305000-a4fab200-dbb4-11e9-9228-20b47deb9fec.png)
case req <- requestJob{chunk: c, data: data}: // request the chunk
				select {
				case <-ctx.Done():
					break loop
				case assemble <- data: // and hand over the data channel to the assembler
				}

**Comment by folbricht** [comment]
Thanks for pointing that out. There was actually another change needed to ensure untar stops on error during the assembly stage.

Handled in https://github.com/folbricht/desync/pull/127
