### ISSUE TITLE
about performance issue

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#13]
Hello, 
i continue our tests about desync, and now in term of performance in comparaison of our actual solution to deploy our images.
Tests shows us that read image block from qemu point of view is more slowy with desync  than nbd for example. This is a normal behaviour, but we would want to  known where , in your experience, we can improve desync performance, for our usage 

1 - Is http/http2 too bad as  data small block transfert, should we try to dev a " nbd chunk server"  ?
( with -c localdisk with mount-index, performance is better  than with -s httplocalstore , so the http protocol header, latence is the issue in this case ) 
2 - desync mount-index and chunk-server seems to create 10 theads by default, is it necessary ? ( reduce cpu usage )
3 - is desync is optimized to find chunk for very big store ? ( 500 G of ~ 64k chunk size : default  ) ?
4 - other ?

Regards, 
Nicolas

**Comment by charles-dyfis-net** [comment]
@folbricht, ...what are your thoughts on setting up a mailing list, so we stop getting things that aren't bugs or feature requests filed as tickets?

**Comment by limbo127** [comment]
Hello, for your attention, test on 10G blob 
desync cat   ~ 100 s
desync mount-index  +  cat on fuse mount file : ~ 135 s 
do you think fuse mount can be optimize

*I do not test extract because of the write part of file.

**Comment by limbo127** [comment]
ok.
thanks
