### ISSUE TITLE
Some bugfix

### ISSUE THREAD

**Issue by BDZenix** [folbricht/desync#132]
![image](https://user-images.githubusercontent.com/16330887/67256036-a242f380-f4b7-11e9-857d-d7ba77abe319.png)
In CreateFile function in localfs.go, if dst is already exists and is executed by some process (include desync its self), there would be a "text file busy" error produced by os.OpenFile(). So we should unlink it first.
![image](https://user-images.githubusercontent.com/16330887/67256157-50e73400-f4b8-11e9-9102-ec316470a603.png)
In CreateDir function, dst maybe a symlink, so we should use os.Lstat() instead of os.Stat()

**Comment by folbricht** [comment]
Thanks for that. Opened https://github.com/folbricht/desync/pull/133 using os.Remove() rather than syscall.Unlink()

**Comment by BDZenix** [comment]
An interesting thing, what if there is a non-empty dir? Use os.RemoveAll() instead?

**Comment by BDZenix** [comment]
![image](https://user-images.githubusercontent.com/16330887/67287205-3ee3b080-f50d-11e9-9ce2-5212d1fcacf0.png)
![image](https://user-images.githubusercontent.com/16330887/67287366-96821c00-f50d-11e9-96ac-01a54b2c64e2.png)

Another fix, keep consistent with casync

**Comment by folbricht** [comment]
I'm not seeing the difference in the mtree filename code. Can you point me to it? The highlighted bit looks equivalent

**Comment by BDZenix** [comment]
This is the remote origin version, the version above is my bug fixed version~
![image](https://user-images.githubusercontent.com/16330887/67452562-35199480-f656-11e9-9bc7-eac205598dcf.png)

**Comment by folbricht** [comment]
Thanks for taking the time to bring those issues up. It's all merged in now.
