### ISSUE TITLE
Add support for tar on Windows

### ISSUE THREAD

**Issue by folbricht** [folbricht/desync#136]
Since https://github.com/folbricht/desync/pull/135, there's limited support for `untar` on Windows. It should also be possible to support `tar` by implementing the Next() method in localfs.go

**Comment by NickTikhonov** [comment]
Hey @folbricht - are there any plans to implement this in the near future? How big do you think this change is - I am very interested in using your library, but I need full Windows support for `tar` and `untar`. Happy to contribute if adding this is straightforward :)

**Comment by folbricht** [comment]
This should be fairly straightforward actually. In fact, untar support was added in https://github.com/folbricht/desync/pull/135 already, it's just missing the tar bit. I can take a look at this the next couple of days.

**Comment by NickTikhonov** [comment]
Great, thank you @folbricht!

**Comment by folbricht** [comment]
@NickTikhonov A first version has been implemented on the issue-136 branch (https://github.com/folbricht/desync/tree/issue-136). Would you be able to try that out and let me know if anything's missing? One thing I haven't been able to try out is the handling of symlinks on Windows 10 (don't have one handy to try).

**Comment by NickTikhonov** [comment]
Amazing, sure - I can try it out! Are there any specific instructions for installing the package on Windows? I had some issues with the standard `go get`

**Comment by NickTikhonov** [comment]
If not, I can provide more details

**Comment by folbricht** [comment]
It's been a while since I setup my Windows VM, but I think the only thing needed is a gcc compiler (see https://github.com/folbricht/desync/issues/72 for a link). As for building, once gcc is in the path it should work if you simply clone the repo somewhere, checkout the branch, then go to desync/cmd/desync and run `go build`

**Comment by NickTikhonov** [comment]
@folbricht I managed to get compilation working after installing `gcc (rubenvb-4.8.0) 4.8.0`. Tarring seems to work pretty well - tested with a 10GB directory. However, I have encountered some transient issues when running `untar`, which seem to resolve themselves when rerunning. This makes me think that the tooling could be improved with retry logic on some of these write operations:

```
C:\Users\nicktikhonov\Documents\projects\desync-test
λ desync untar 2019-09-26.manifest downloaded -i -c cache -s store
Unpacking [============================================>--------------------------------------------------------]  44.10% 33s Error: failed to store in local cache: rename cache\b8d7\.tmp-cacnk.1990028575 cache\b8d7\b8d7d340618ecf7d08c0a9d24f4487be539accf7978e48cfc3f10af97ff7e61e.cacnk: Access is denied.

C:\Users\nicktikhonov\Documents\projects\desync-test
λ desync untar 2019-09-26.manifest downloaded -i -c cache -s store
Unpacking [=============================================>--------------------------------------------------------]  44.13% 7s Error: failed to store in local cache: rename cache\9323\.tmp-cacnk.4274893116 cache\9323\932336604d7a3714bf46a09f069b3c05a4e3942da3b756c282ac9a777421f0aa.cacnk: Access is denied.

C:\Users\nicktikhonov\Documents\projects\desync-test
λ desync untar 2019-09-26.manifest downloaded -i -c cache -s store
Unpacking [=====================================================================>-------------------------------]  68.73% 25s Error: failed to store in local cache: rename cache\558c\.tmp-cacnk.322706907 cache\558c\558c0bd77610607da4388091ef145ca854dfea84812f7e9031fa2f1a75c1cc95.cacnk: Access is denied.

C:\Users\nicktikhonov\Documents\projects\desync-test
λ desync untar 2019-09-26.manifest downloaded -i -c cache -s store
Unpacking [=======================================================================================>-------------]  86.35% 25s Error: chunk id c60666f7e1f4d8b024193571e6119cdd98b6fceb71bef2ea8d7be2becfcee4c0 does not match its hash 0000000000000000000000000000000000000000000000000000000000000000

C:\Users\nicktikhonov\Documents\projects\desync-test
λ desync untar 2019-09-26.manifest downloaded -i -c cache -s store
Unpacking [=====================================================================================================] 100.00% 26s

C:\Users\nicktikhonov\Documents\projects\desync-test
λ
```

**Comment by folbricht** [comment]
Thanks for trying that. I have an idea of where this happens. Windows is a bit picky about renaming files while they're open. Saw something similar before there. Don't think there needs to be a retry here, but a re-ordering of Close() and Rename() potentially.

Do you see this when running without `-c cache` at all?

**Comment by NickTikhonov** [comment]
Ran this a few times without the cache, and it works just fine :)

**Comment by folbricht** [comment]
This is very likely a bug in the cache, unrelated to `tar`. And I expect it to be fixed by re-ordering of file operations. Will take a look soon.

**Comment by folbricht** [comment]
The root cause is actually that Windows doesn't have an atomic rename operation (at least I couldn't find one), so writing the same chunks to the cache (or store) at the same time is likely to fail.

@NickTikhonov I pushed a change that should ensure that chunks aren't written to the cache concurrently on Windows which should fix the above. Could you try that again?

**Comment by NickTikhonov** [comment]
Hey @folbricht - thanks for the support! I will give it a shot right now and report the results

**Comment by NickTikhonov** [comment]
Happy to report that it seems to be working well now :)

**Comment by folbricht** [comment]
Thanks for trying it out, going to merge it to master
