### ISSUE TITLE
Retrieve AWS credentials from ~/.aws/credentials

### ISSUE THREAD

**Issue by Joe-Improbable** [folbricht/desync#144]
Currently desync doesn't fall back to using `~/.aws/credentials` if no other methods of providing credentials is used.

The code for falling back to the default credential location exists (`credentials.go:103` `Retrieve()`) however it is not used. 

Is there reason this functionality isn't used?

**Comment by folbricht** [comment]
Resolved in https://github.com/folbricht/desync/pull/145
