### ISSUE TITLE
Windows - Writededupqueue race condition

### ISSUE THREAD

**Issue by Joe-Improbable** [folbricht/desync#149]
I believe there is a race condition on Windows when using a Cache.

The root cause is that the `Writededupqueue.go` uses the `getChunkQueue` for both `StoreChunk`, `GetChunk` and `HasChunk`

I believe `HasChunk` should instead be using the currently unused `hasChunkQueue`

The race condition:

| Thread 1        | Thread 2           |
| ------------- |:-------------:|
| HasChunk    |  | $1600 |
| Stores request in requests map (Locks getChunkQueue mutex)  | StoreChunk
| | Request is in flight (Mutex is locked so waits) 
| Finds chunk is missing and returns `chunkMissing` on channel |      |
| removes request from request map  (Unlocks mutex)  |
| | Receives a `chunkMissing` error on the channel and returns causing `cache.GetChunk` to return a `chunkMissing` error

I'll raise a PR for my fix.

Let me know if you need a better explanation

**Comment by folbricht** [comment]
I think you may be right about this potentially causing issues. It'd be nice if we didn't need the write-dedupe-queue at all to work around Windows not supporting atomic file renames. If there was a solution to that issue (renaming multiple files to the same name concurrently), the queue could be removed to simplify that code path again.

**Comment by Joe-Improbable** [comment]
a
