### ISSUE TITLE
Issue with symlinks

### ISSUE THREAD

**Issue by bailer** [folbricht/desync#153]
Hello,

I'm trying out various tools to distribute container images with de-duplication of data in mind. I tried using tar/untar but when untaring I get 
`Error: chown <path/to/symlink>: no such file or directory`
which is a symlink in the original folder. 

Since this issue doesn't occur when using normal tars, I'm a bit curious to why this happens. I also haven't really understood the benefit with the catar compared to normal tar. Is it just to have convenient folder->tar->chunks and chunks->tar->folder commands (reducing the amount of steps from 4 to 2) or does it bring more value that I haven't grasped yet? 

I also noticed that with casync you are able to mount an archive to access it's contents while desync mounts the blob so I need to unpack it anyway. Is there a point to this or just unprioritized?

**Comment by folbricht** [comment]
Do you have a way to easily repro the symlink issue? Was that an untar of a catar file made by desync or something else?

Wrt the advantages of catar, one would be what you asked about next. The ability to mount them. desync doesn't currently support mounting catar/caidx files. Mounting blobs was an easy implementation, specifically for mounting VM images and a full implementation of mounting catar like casync just hasn't been done yet. It's possible, and it was planned but not done at this point.

**Comment by bailer** [comment]
It's all done with desync,

It seems to happen if the symlink is unpacked before the real file has been unpacked. If I create a folder with 2 files, one linking to the other and the symlink has a filename which is alphabetically before the real file, it fails. If the symlink is after the real file alphabetically it works.

Steps:
desync tar -i -s chs.castr ids.castr/foo.caidx foo
desync untar -s ch.castr -i id.castr/foo.caidx bar

where foo is a folder as I described it

**Comment by folbricht** [comment]
Thanks for the repro, I'll take at it tonight.

**Comment by folbricht** [comment]
Should be fixed in https://github.com/folbricht/desync/commit/e72efd4f61f25a6d2f057f5255a4c69d9b217822 This likely broke when GNU tar support was added.

**Comment by bailer** [comment]
Cool! Thanks for the quick fix, means I can continue my evaluations :)
