### ISSUE TITLE
Intermittent EOF errors while sending chunks over HTTPS

### ISSUE THREAD

**Issue by TLATER** [folbricht/desync#168]
Hi, I'm trying to use desync for large file transfers across what appears to be a fairly unstable network connection.

From some initial testing it reduces file transfer speed a lot - but only if the transfer is not interrupted. The latter happens frequently...

This seems to be separate from #159 - the logs indicate `attempt=1`, and EOF isn't an HTTP response. Nonetheless, when I invoke the command repeatedly, it will eventually upload all chunks - it just wastes a lot of time checking whether the chunks have already been uploaded again.

My configuration is set to retry on error:

```json
{
    "store-options": {
        "error-retry": 5
   }
}
```

This leaves me with two questions...

1. Can this error be treated as an intermittent error as well, and trigger the "error-retry" option, so that the upload doesn't have to be restarted?
2. Is there already a way to resume an upload if it is interrupted? This is of course racy if chunks are ever removed from the remote, but I think this is rather uncommon.

I'm happy to take on implementing anything that needs to be done for this, I just want to gauge how feasible this is before I jump in, or whether I'm running into something expected.

Here's an excerpt from my logs (slightly doctored to remove domain and make things a bit more readable):

```
DEBU[2630] response received           attempt=1 method=HEAD statusCode=404 url="fd40/fd40eac29af054514a678db585dd8eb837c1f9359b9fcca12daf82f6dde86083.cacnk"
DEBU[2630] sending request             attempt=1 method=PUT url="fd40/fd40eac29af054514a678db585dd8eb837c1f9359b9fcca12daf82f6dde86083.cacnk"
ERRO[2630] error while sending request attempt=1 error="Put \"fd40/fd40eac29af054514a678db585dd8eb837c1f9359b9fcca12daf82f6dde86083.cacnk\": EOF" method=PUT url="fd40/fd40eac29af054514a678db585dd8eb837c1f9359b9fcca12daf82f6dde86083.cacnk"
DEBU[2630] failed, giving up           attempt=1 method=PUT url="fd40/fd40eac29af054514a678db585dd8eb837c1f9359b9fcca12daf82f6dde86083.cacnk"
DEBU[2630] response received           attempt=1 method=PUT statusCode=200 url="1047/10471d565036d6eb2c91de74e393f0fbeff18c0db2c113f16e038795bd0fdb5f.cacnk"
Storing
[====================================================================================================================================>-----------------------------------------------------------]
69.04% 19m37s
DEBU[2631] response received           attempt=1 method=HEAD statusCode=404 url="c4fd/c4fd408cb256c14a2991c566e3822fd054a01f668d16befdfe9e41b3354ce21a.cacnk"
DEBU[2631] sending request             attempt=1 method=PUT url="c4fd/c4fd408cb256c14a2991c566e3822fd054a01f668d16befdfe9e41b3354ce21a.cacnk"
DEBU[2631] response received           attempt=1 method=HEAD statusCode=404 url="2976/297644e52cd476020738c365bf67b002dcd64d60dabc92d346c0d9d77d75bad4.cacnk"
DEBU[2631] sending request             attempt=1 method=PUT url="2976/297644e52cd476020738c365bf67b002dcd64d60dabc92d346c0d9d77d75bad4.cacnk"
Storing
[====================================================================================================================================>-----------------------------------------------------------]
69.04% 19m37s
DEBU[2631] response received           attempt=1 method=PUT statusCode=200 url="1b91/1b915b02db50a575865a9c25fda03eddbab1f281815e8d94701f9e23fd30eb70.cacnk"
DEBU[2631] response received           attempt=1 method=HEAD statusCode=404 url="/c12a/c12ac59618fbaf53be20a0806e23d7a8c80df3b07c0dd9f80dccb0b92dd08f34.cacnk"
DEBU[2631] sending request             attempt=1 method=PUT url="c12a/c12ac59618fbaf53be20a0806e23d7a8c80df3b07c0dd9f80dccb0b92dd08f34.cacnk"
Storing
[====================================================================================================================================>-----------------------------------------------------------]
69.04% 19m36s
DEBU[2631] response received           attempt=1 method=PUT statusCode=200 url="2c09/2c098e268c73344f713f84e691020b36668f006c9ceff4ea31eb50ca9e989357.cacnk"
DEBU[2631] response received           attempt=1 method=PUT statusCode=200 url="a5df/a5dffeec378fa0f72ae1e8d91594b7173239b958036141c5a904c7d214d9e867.cacnk"
Storing
[====================================================================================================================================>-----------------------------------------------------------]
69.04% 19m36s
DEBU[2631] response received           attempt=1 method=PUT statusCode=200 url="c12a/c12ac59618fbaf53be20a0806e23d7a8c80df3b07c0dd9f80dccb0b92dd08f34.cacnk"
Storing
[====================================================================================================================================>-----------------------------------------------------------]
69.04% 19m36s
DEBU[2632] response received           attempt=1 method=PUT statusCode=200 url="a972/a9722587d373f6299df032bf5d074cf34cbf7d401ce78382c9559606cfaf9c3a.cacnk"
Storing
[====================================================================================================================================>-----------------------------------------------------------]
69.04% 19m36s
DEBU[2632] response received           attempt=1 method=PUT statusCode=200 url="c4fd/c4fd408cb256c14a2991c566e3822fd054a01f668d16befdfe9e41b3354ce21a.cacnk"
Storing
[====================================================================================================================================>-----------------------------------------------------------]
69.04% 19m36s
DEBU[2632] response received           attempt=1 method=PUT statusCode=200 url="2976/297644e52cd476020738c365bf67b002dcd64d60dabc92d346c0d9d77d75bad4.cacnk"
Storing
[====================================================================================================================================>-----------------------------------------------------------]
69.04% 19m35s
DEBU[2633] response received           attempt=1 method=PUT statusCode=200 url="fb9a/fb9ad78917f31b8d86d96e5523de3bb9685837335bf29ef5579ccce043e5c099.cacnk"
Storing
[====================================================================================================================================>-----------------------------------------------------------]
69.04% 43m48s
Error: fd40/fd40eac29af054514a678db585dd8eb837c1f9359b9fcca12daf82f6dde86083.cacnk: Put
"fd40/fd40eac29af054514a678db585dd8eb837c1f9359b9fcca12daf82f6dde86083.cacnk": EOF
```

**Comment by folbricht** [comment]
Just looked at the code and it should consider every error (incl EOF) as retry-able. This line here seems to say that it's only allowing one failure:
```
DEBU[2630] failed, giving up           attempt=1 method=PUT url="fd40/fd40eac29af054514a678db585dd8eb837c1f9359b9fcca12daf82f6dde86083.cacnk"
```

The issue might be your config file. The example you gave doesn't quite have the correct structure. `store-options` is actually a map that's indexed by the store URL like so

```json
{
  "store-options": {
    "https://192.168.1.1/store": {
      "error-retry": 5
    }
}
```

That should work. If not, we can trace if through the code and see why it's not setting the retry count.

**Comment by folbricht** [comment]
As for your second question of diff upload of chunks, it's not exactly what you asked but there's a couple things that you might want to consider. So the whole process typically consists of two steps, chunking and uploading. You can do them separately so no need to re-chunk if the upload fails.

```
desync make <index> <blob>
desync chop -s <store> <index> <blob>
```

You can run the `chop` command multiple times if it fails, it'll use the index you produced in step 1.

Another thing that may come in handy for you if you have a large number of chunks, a slow connection and you wanted to upload another file that is similar to one you uploaded earlier, take a look at the `--ignore` option of the `chop` command. So if you had to upload 2 files that have a lot in common, you upload the first as you do now. But for the 2nd you can use `desync chop --ignore <index1.caibx>` since you know those have already been uploaded. It's going to only upload chunks that weren't already in the first.

**Comment by TLATER** [comment]
Thanks for the quick response! I checked my logs and it seems that desync did complain about an error in the config, I think it'll likely be that - can't actually test again until Monday unfortunately, but I'll close this as soon as I know.

I'm not sure why I thought that would be a valid configuration, sorry about that.

Also thanks a lot for that other suggestion - not exactly what I was looking for in terms of interrupted uploads, but presumably this will also prevent lots of unnecessary HEAD requests, that should speed things up even further :)

**Comment by TLATER** [comment]
Alright, that took a while to get through, sorry, inefficient bureaucracy... The uploads are working perfectly, I have not seen an EOF yet. Thanks!
