### ISSUE TITLE
enhancement: mtree on directory

### ISSUE THREAD

**Issue by garyvdm** [folbricht/desync#171]
Please can you add the ability to run mtree on a directory without first creating a tar.

**Comment by folbricht** [comment]
@garyvdm I put a draft implementation in the `issue-171` branch. Would you mind trying that out to make sure it works as expected? Internally it does in fact perform a tar operation (without writing to disk). So the output should always be identical to what a tar would produce.

**Comment by garyvdm** [comment]
Sorry for then slow response.

I've just tested latest from master, and it works great. 

Much Thanks!
