### ISSUE TITLE
desync untar  -i doesn't return when chunks missing

### ISSUE THREAD

**Issue by aspeteRakete** [folbricht/desync#18]
When doing an untar with a malformed store url the process hangs and doesn't return. Sending SIGINT doesn't seem to work. I have to kill the process.

**Comment by aspeteRakete** [comment]
SIGQUIT: quit
PC=0x4616a1 m=0 sigcode=128

goroutine 0 [idle]:
runtime.futex(0xc37f08, 0x0, 0x0, 0x0, 0x7fff00000000, 0x41c7a9, 0x0, 0x0, 0x7ffffbdac9f8, 0x418c4b, ...)
	/usr/lib/go-1.10/src/runtime/sys_linux_amd64.s:526 +0x21
runtime.futexsleep(0xc37f08, 0x7fff00000000, 0xffffffffffffffff)
	/usr/lib/go-1.10/src/runtime/os_linux.go:45 +0x4b
runtime.notesleep(0xc37f08)
	/usr/lib/go-1.10/src/runtime/lock_futex.go:151 +0x9b
runtime.stoplockedm()
	/usr/lib/go-1.10/src/runtime/proc.go:2096 +0x8c
runtime.schedule()
	/usr/lib/go-1.10/src/runtime/proc.go:2488 +0x2da
runtime.park_m(0xc42007e780)
	/usr/lib/go-1.10/src/runtime/proc.go:2599 +0xb6
runtime.mcall(0x75f730)
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:351 +0x5b

goroutine 1 [select, 7 minutes]:
io.(*pipe).Read(0xc420271d60, 0xc4201cf150, 0x8, 0x8, 0x0, 0xc42032264c, 0x799980)
	/usr/lib/go-1.10/src/io/pipe.go:50 +0x115
io.(*PipeReader).Read(0xc42000e0d8, 0xc4201cf150, 0x8, 0x8, 0xc4202451c0, 0x10, 0x10)
	/usr/lib/go-1.10/src/io/pipe.go:127 +0x4c
io.ReadAtLeast(0x86ed00, 0xc4202451c0, 0xc4201cf150, 0x8, 0x8, 0x8, 0xc4202451c0, 0xc4202451c0, 0x7ef700)
	/usr/lib/go-1.10/src/io/io.go:309 +0x86
io.ReadFull(0x86ed00, 0xc4202451c0, 0xc4201cf150, 0x8, 0x8, 0x8, 0x0, 0x0)
	/usr/lib/go-1.10/src/io/io.go:327 +0x58
github.com/folbricht/desync.reader.ReadUint64(0x86e220, 0xc42000e0d8, 0x10, 0xc420244d80, 0x0)
	/root/go/src/github.com/folbricht/desync/reader.go:16 +0xc8
github.com/folbricht/desync.reader.ReadHeader(0x86e220, 0xc42000e0d8, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/folbricht/desync/reader.go:44 +0x39
github.com/folbricht/desync.(*FormatDecoder).Next(0xc4201c1928, 0xc420444868, 0x32a, 0xc4201bcf30, 0xc4200aa468)
	/root/go/src/github.com/folbricht/desync/format.go:153 +0x6c
github.com/folbricht/desync.(*ArchiveDecoder).Next(0xc4201c1928, 0xc42007ad80, 0x0, 0x7fbddb39d1d0, 0x45a5b0)
	/root/go/src/github.com/folbricht/desync/archive.go:80 +0x13f5
github.com/folbricht/desync.UnTar(0x872180, 0xc42009ef40, 0x86e220, 0xc42000e0d8, 0x7ffffbdad841, 0x6, 0x10000, 0x40000)
	/root/go/src/github.com/folbricht/desync/untar.go:30 +0x17f
github.com/folbricht/desync.UnTarIndex(0x872180, 0xc42009ef40, 0x7ffffbdad841, 0x6, 0x30, 0x96824d9c7b129ff9, 0xa000000000000000, 0x4000, 0x10000, 0x40000, ...)
	/root/go/src/github.com/folbricht/desync/untar.go:237 +0x499
main.untar(0x872180, 0xc42009e540, 0xc4200a0020, 0x9, 0x9, 0x0, 0x0)
	/root/go/src/github.com/folbricht/desync/cmd/desync/untar.go:80 +0x728
main.main()
	/root/go/src/github.com/folbricht/desync/cmd/desync/main.go:81 +0x740

goroutine 19 [syscall, 3 minutes]:
os/signal.signal_recv(0x871340)
	/usr/lib/go-1.10/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/lib/go-1.10/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/lib/go-1.10/src/os/signal/signal_unix.go:28 +0x41

goroutine 20 [select, 7 minutes, locked to thread]:
runtime.gopark(0x841fe8, 0x0, 0x8277ff, 0x6, 0x18, 0x1)
	/usr/lib/go-1.10/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc42002d750, 0xc42007a300)
	/usr/lib/go-1.10/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/usr/lib/go-1.10/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1

goroutine 15 [chan receive, 7 minutes]:
github.com/folbricht/desync.UnTarIndex.func4(0xc4200aa780, 0xc42000e0e0, 0xc420269680)
	/root/go/src/github.com/folbricht/desync/untar.go:228 +0x84
created by github.com/folbricht/desync.UnTarIndex
	/root/go/src/github.com/folbricht/desync/untar.go:226 +0x448

rax    0xca
rbx    0xc37dc0
rcx    0x4616a3
rdx    0x0
rdi    0xc37f08
rsi    0x0
rbp    0x7ffffbdac9c0
rsp    0x7ffffbdac978
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc42002d768
r13    0xff
r14    0xff
r15    0xf
rip    0x4616a1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

**Comment by folbricht** [comment]
Thanks for the report. The issue here is that in the error-case, one of the channels doesn't get closed and it just hangs there forever. It's this line here https://github.com/folbricht/desync/blob/master/untar.go#L228

Quick fix is to add `close(r.data)` to the error handlers in the worker goroutines. It'd be prettier if that functionality moved off into a function so we could use defer, but it'll do for now.

**Comment by folbricht** [comment]
Should be fixed by https://github.com/folbricht/desync/commit/8fe3f0bb7e62f38902015336d348ae01a89a046c

**Comment by aspeteRakete** [comment]
Yes. Just tested it with my Scenario. Works! 👍
