### ISSUE TITLE
build dependency minio/minio-go v6 not existing

### ISSUE THREAD

**Issue by flomo29** [folbricht/desync#183]
When i run: **go get -v github.com/folbricht/desync**

I got:
cannot find package "github.com/minio/minio-go/v6" in any of:
cannot find package "github.com/minio/minio-go/v6/pkg/credentials" in any of:

I tried to download v6 manualy, but the version you referenced in the go dependency file is not existing anymore.
Only another v6 exists or v7.

GO111MODULE=on go get github.com/minio/minio-go/v6
go: github.com/minio/minio-go/v6 upgrade => v6.0.57

**Comment by folbricht** [comment]
Please make sure you run it like this: `GO111MODULE=on go get -v github.com/folbricht/desync/cmd/desync` The referenced version of Minio (v6.0.57) is stil there, it's tagged as it should be.
If the above doesn't work, check your Go version, it should be 1.15+.

**Comment by flomo29** [comment]
Thank you. It works now!
