### ISSUE TITLE
Example in help text in tar subcommand error

### ISSUE THREAD

**Issue by Silcet** [folbricht/desync#184]
I just started using desync and I noticed that on the tar subcommand the help text suggests the example below. However, this errors out saying that the directory you pass as an argument "is a directory".
https://github.com/folbricht/desync/blob/e528127e56c793fd01fcece8559fa081c450c5ce/cmd/desync/tar.go#L39

I'm guessing that the fix would be the following:
```
Examples:
  desync tar documents.catar $HOME/Documents
  desync make -s /path/to/local docs.caibx documents.catar
```

**Comment by folbricht** [comment]
Well spotted, thank you. It was intended to show the combined operation `desync tar -i ...` which doesn't first create the catar. Your suggestion of using 2 commands is correct as well. I added a paragraph about what `-i` does, hope that makes it more clear.
