### ISSUE TITLE
~/.aws/credentials now mandatory even pulling from publicly-readable source?

### ISSUE THREAD

**Issue by charles-dyfis-net** [folbricht/desync#190]
I have a user report of a `failed to load shared credentials file: open /home/<username>/.aws/credentials: no such file or directory` from a user trying to download from a publicly-shared `s3+https://...` URI (that, being public, should not require any credentials), resolved by downgrading to an older version of desync.

**Comment by folbricht** [comment]
That was my bad. It should be fixed in https://github.com/folbricht/desync/pull/191 but don't have a public bucket handy to try it out at the moment. If you could test it real quick that'd be great. Going to add a test and turn it into 0.9.2 then

**Comment by folbricht** [comment]
It's been merged and tagged as v0.9.2
