### ISSUE TITLE
Support writing to block devices

### ISSUE THREAD

**Issue by om26er** [folbricht/desync#193]
For A/B partitioning it's very useful to be able to directly write to the block device instead of first reconstructing the image and then writing that to the actual partition (using dd). casync supports that, however it's slow when downloading chunks from S3, desync on the other hand has parallel downloads, so I am looking into desync and it seems that's an important missing feature.

What are the plans to support that ?

**Comment by folbricht** [comment]
That should already be supported, can you try it? You would have to use the `-k` option update the output file in-place, but other than that it should just work.

**Comment by om26er** [comment]
yep, it works. I was wrong to assume that. Thanks
