### ISSUE TITLE
verify-index does not work on block device

### ISSUE THREAD

**Issue by om26er** [folbricht/desync#194]
I am trying to verify if a caibx corresponds to a system partition, but it seems the only way to check is to actually call `desync extract` and wait for it to fail.

```
root@raspberrypi4-simple-things:~# desync verify-index /dev/mmcblk0p2.caibx /dev/mmcblk0p2
[-----------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00% 0s
Error: index size (426856448) does not match file size (0)
```

**Comment by folbricht** [comment]
Good catch. I have a possible fix on the `issue-194` branch, but nothing to properly test right now. Can you try that and see if it addresses your issue?

**Comment by om26er** [comment]
Thanks for the quick PR. I have verified your PR fixes the issue.
