### ISSUE TITLE
Why are cacnk chunks stored differently locally and on S3? 

### ISSUE THREAD

**Issue by bradley-curran** [folbricht/desync#22]
I've stored a chunked directory using the `tar` command and created a store both locally and on S3. 

The local store has a folder for each hashed chunk's first four characters:

```
./ab58/ab58876768a83ee7fb116492a772e8bd70d1f2a1afdfbda2b7b6fe746648cbcb.cacnk
./ab6e/ab6e5c7b5eaa344020e020ec06513e4414bfe2125747a258bae01420b2f03c33.cacnk
./ab71/ab71b366193d088de37695d16bb0a9982090b376c67f155003f8f801e46b7dc3.cacnk
./ab71/ab71f56e030f2b65e4db56a2e6319fc15c505aeda9a0f7e7fb0b4dcfdf6e9753.cacnk
./ab83/ab8359f6e51788e433ec9ee19eafbfbe2ec4584ff8528f59c4a3062e648ee1d6.cacnk
./ab89/ab89a246305e39a9cf3b41e4a632a6955c4ff171747a20b1de1ad2b24b55ebdb.cacnk
```

However the same tar command using S3 produces a different structure: 

```
./ab58876768a83ee7fb116492a772e8bd70d1f2a1afdfbda2b7b6fe746648cbcb.cacnk
./ab6e5c7b5eaa344020e020ec06513e4414bfe2125747a258bae01420b2f03c33.cacnk
./ab71b366193d088de37695d16bb0a9982090b376c67f155003f8f801e46b7dc3.cacnk
./ab71f56e030f2b65e4db56a2e6319fc15c505aeda9a0f7e7fb0b4dcfdf6e9753.cacnk
./ab8359f6e51788e433ec9ee19eafbfbe2ec4584ff8528f59c4a3062e648ee1d6.cacnk
./ab89a246305e39a9cf3b41e4a632a6955c4ff171747a20b1de1ad2b24b55ebdb.cacnk
```

Why not add the prefix to the S3 version as well? Does casync have the same functionality?

**Comment by folbricht** [comment]
For the local case, that's what casync does and we tried to be compatible with it, using the same layout. S3 doesn't really need that so I didn't think of doing it the same way. Do you have a use case where this matters?
It's not difficult to add the prefix, but the issue is that people might be using the flat layout already and I don't have a good idea how to tell the tool when to add the prefixes. A new command-line option doesn't seem like the right way, perhaps something in the S3 store URL?

**Comment by bradley-curran** [comment]
One use case I can think of is pruning the S3 store. 

eg: I have uploaded two directories to S3 using the following:

```bash
# directories images/a and images/b have some similar files
# upload directory a
$ desync tar -i -s s3+https://s3-us-west-2.amazonaws.com/bucket/store a.caidx images/a
# upload directory b
$ desync tar -i -s s3+https://s3-us-west-2.amazonaws.com/bucket/store b.caidx images/b
```

Now I want to remove `images/b` from the S3 cache. 

`desync prune` only works on local directories. 

As a workaround I could do a prune on the local store and run the AWS CLI `aws s3 sync --delete` from the local store the S3 bucket to delete unrequired chunks. 

However because the structure is different on S3 I can't run a sync between the local store and S3.

**Comment by folbricht** [comment]
Would `prune` supporting s3 stores directly work for you? That seems like a cleaner way of dealing with this. Shouldn't be hard to implement.

**Comment by bradley-curran** [comment]
This sounds good. 

Alternatively (or on top of) could we implement a configuration file? If there's a configuration file the defaults can stay as-is while custom configuration can be done by the end user. 

I'm not sure if the config file approach would break the project's aims though.

**Comment by limbo127** [comment]
hello, 
we are in the same case. our problematics are : 
- we must using desync make on local store , then synchronise to s3 bucket with aws sync , for certains scenario 
- and we must using desync make on s3 store with s3+https , on the same global s3 store .

so I think we need an option to specify the path of s3 object key or local store ( rep is necessary for performance issue i think)   

regards, 
Nicolas

**Comment by folbricht** [comment]
I'm going to take a look into aligning the structure used in s3 stores with that of local stores. Even HTTP stores use a prefix and `.cacnk` extension format, you're right that s3 should do the same for consistency and to allow for operating on those stores outside of desync.

**Comment by folbricht** [comment]
https://github.com/folbricht/desync/pull/23 implements support for S3 stores in the `prune` command.

@bradley-curran @limbo127 There's now a branch `s3-layout` that uses the consistent layout in S3 stores as well, which should allow you to copy stores between local and S3. Would you be able to check it out and let me know if that works for you? Only got a small minio server here to try. Note: there's a `upgrade-s3` command that lets you convert from the old format. Should just be
```
desync upgrade-s3 -s s3+http://192.168.1.1:9000/store
```

**Comment by folbricht** [comment]
@limbo127 Is that reproducible and does it happen when you build off master. It looks unrelated, and if so, please file a separate issue for this. (not made any changes around that so surprised to see it).

**Comment by limbo127** [comment]
sorry, I pass with a proxy that log code 400, message Bad HTTP/0.9 request type, but it"s not relative to desync. 

new s3-layout seems to be work . ( 100G in two image blob as test )

**Comment by folbricht** [comment]
https://github.com/folbricht/desync/pull/24 brings the layout of chunk stores in line with that of local or HTTP stores.
