### ISSUE TITLE
Plans for a new v0.9.3 release

### ISSUE THREAD

**Issue by RyuzakiKK** [folbricht/desync#224]
Desync just landed on the official (community) Arch Linux repositories https://archlinux.org/packages/community/x86_64/desync/
However the latest tagged version is currently the v0.9.2, that is more than a year old.

Is there any plan to tag a newer v0.9.3 to include all the latest changes from master?

**Comment by folbricht** [comment]
Thanks for the reminder. I haven't been keeping the release tags updated. Just tagged master https://github.com/folbricht/desync/releases/tag/v0.9.3
