### ISSUE TITLE
[Feature/Question] Specifying Offset with In-place Extraction

### ISSUE THREAD

**Issue by bearrito** [folbricht/desync#250]
Is it possible (or desirable) to specify in-place extraction with an offset? 
Today in our A/B setup we do something equivalent to 
```
xz -d -c $IMAGE_PATH | sudo dd skip=$SKIP_BLOCKS of=$PARTITION status=progress
```
Where skip blocks equates to the size of the MBR.

**Comment by charles-dyfis-net** [comment]
Possible, surely, if you create and target a loopback device with an offset
configured.

**Comment by bearrito** [comment]
@charles-dyfis-net Hmm, I'm not familiar with that approach. But it sounds like there is some known technique I can investigate that's outside of desync. Thanks for the lead.
