### ISSUE TITLE
Unknown S3 bucket lookup type error message uses `s` instead of `ls`

### ISSUE THREAD

**Issue by dhausauer-flx** [folbricht/desync#266]
At https://github.com/folbricht/desync/blob/2cd76a54d4a79a2e703d22f033ad7300e59a1dab/cmd/desync/store.go#L141

```
return nil, fmt.Errorf("unknown S3 bucket lookup type: %q", s)
```

should read:

```
return nil, fmt.Errorf("unknown S3 bucket lookup type: %q", ls)
```

**Comment by folbricht** [comment]
Fixed in https://github.com/folbricht/desync/pull/267, thanks

**Comment by dhausauer-flx** [comment]
Thank you!
________________________________
