### ISSUE TITLE
Desync v0.9.6

### ISSUE THREAD

**Issue by RyuzakiKK** [folbricht/desync#268]
Would it be possible to tag a new release of Desync?

We are waiting for https://github.com/folbricht/desync/commit/a60262d58f61a014b50dfb2169d0317d91c1bd6c to be included in a release because that would allow us to drop our custom `config.json` file.

Thanks

**Comment by folbricht** [comment]
Done in https://github.com/folbricht/desync/releases/tag/v0.9.6
