### ISSUE TITLE
chown <file>: operation not permitted - untar on a different computer

### ISSUE THREAD

**Issue by bradley-curran** [folbricht/desync#28]
Use case: 

```bash
# this line works fine
computerA $ desync tar -i -s s3+https://s3-us-west-2.amazonaws.com/bucket dir.caidx dir
# this line fails on attempting to change the owner of the base directory
computerB $ desync untar -i -s s3+https://s3-us-west-2.amazonaws.com/bucket dir.caidx dir
```

The following error is printed: 

    chown dir: operation not permitted

I'm assuming the issue is because the UID/GID is different on computerA and computerB. 

Running the command using `sudo` works, but I'd prefer not to do that. 

How can I avoid this issue?

**Comment by folbricht** [comment]
@bradley-curran There's now an option `-no-same-owner` on the untar command that should allow you to run desync as a regular user.
