### ISSUE TITLE
casync unable to read caidx file produced by desync

### ISSUE THREAD

**Issue by folbricht** [folbricht/desync#42]
casync is able to read catar files generated by desync. In theory, caidx files are just chunked catars but casync is currently failing to read those.

**Comment by charles-dyfis-net** [comment]
There's more to creating a .caidx than just chunking a catar; indeed, see systemd/casync#96 asking them to add similar support on their end.

With that not yet implemented, using upstream casync to create a catar and then chunking it creates an archive that upstream casync itself can't read as a caidx:

```
f() (
  set -x
  cleanup() { rm -rf "$testdir"; }
  testdir=$(mktemp -d "${TMPDIR:-/tmp}/casync-test.XXXXXX") || return
  cd "$testdir" || { cleanup; return; }
  mkdir tmp && echo hello >tmp/foo
  casync make tmp.catar tmp
  casync make tmp.caidx tmp
  casync make tmp.catar.caibx tmp.catar
  desync tar tmp-desync.catar tmp
  desync tar -i -s default.castr tmp-desync.caidx tmp
  desync make -s default.castr tmp-desync.catar.caibx tmp.catar
  ln tmp.catar.caibx tmp-invalid.caidx
  casync list tmp.catar
  casync list tmp.caidx
  casync list tmp-invalid.caidx
  casync list tmp-desync.caidx
  desync list-chunks tmp.caidx
  desync list-chunks tmp-invalid.caidx
  desync list-chunks tmp-desync.caidx
  ls -l
  md5sum * 
  cleanup
)
```

Inspecting output of the above, we can draw some conclusions:

- Only an archive initially created by upstream casync as a caidx can be parsed by upstream casync as a caidx; upstream casync itself cannot parse a .catar which it chunked into a .caibx.
- There's no difference between how desync and casync chunk a catar.
- The file desync creates when trying to convert a catar to a caidx 
- The valid and invalid .caidx files have the same length (this rules out location metadata being copied up from the catar to the index).
- The invalid and invalid .caidx files both *refer to the same chunk* (and only refer to exactly one chunk).

This last finding is particularly pertinent -- it means we can just compare the index files themselves to locate our issue -- and in the above simplified test case, there are exactly four bytes that differ between the two files in question: Those immediately following the CaFormatIndex marker.

In a file created as a `.caidx`, these bytes have the values `26 fe ef ff`; created as a `.caibx` with either desync or upstream casync, they're `00 00 00 00`.

Further details pending. :)

**Comment by charles-dyfis-net** [comment]
e67b620310344ee77cbf5616e721070c61bcd206 is a first cut at this. Should not yet be considered submitted for merge.

**Comment by charles-dyfis-net** [comment]
#56, as amended, now passes an interop smoketest for `desync tar -i` as well as `desync make` (the latter of which is something upstream `casync` can't do) -- consider the "should not yet be considered" retracted.

**Comment by folbricht** [comment]
I believe we need to handle the same situation when creating an index from directory in one step with `desync tar -i ...`. That would have to go somewhere in https://github.com/folbricht/desync/blob/1d864f71cd7e0de3f3ab19ef292d526632d63c9b/index.go#L127, look at the first few bytes in the stream to see if it's a catar, then copy the flags from it.

**Comment by charles-dyfis-net** [comment]
I believe I already covered the case with https://github.com/folbricht/desync/pull/56/files#diff-d03dc435598288abaa99cc11fe334a38R117

**Comment by folbricht** [comment]
Yes, didn't realize it at first. It just clones the flags whole (which is a very clean solution). Thank you
