### ISSUE TITLE
Support for remote indexes

### ISSUE THREAD

**Issue by folbricht** [folbricht/desync#49]
This feature should optionally allow for indexes accessed remotely from a central location rather than requiring the index files to be present locally. It should allow remote indexes be accessible via HTTP(S), S3, and SFTP by specifying the location as URL in the command line such as:
```
desync extract -s http://chunk-server/store http://index-server/somefile.caibx somefile
```
All 3 protocols should allow index-file creation (writing).

In order to provide an out-of-the-box solution for HTTP, a new sub-command `index-server` could be created to serve indexes (similar to `chunk-server`). That would allow the index server to be isolated from the chunks, like on a different port or server.

**Comment by limbo127** [comment]
For your information, our indexes files are very big ( ~100M ) , so at this time, we are making chunk of this first index, and store it .

So for an blob image of 200Go  , we are making a index-1 ( ~100M ) , then we are make a  index-2 of index-1 , we obtain a index file of 5M  , that we can download easily

Regards, 
Nicolas

**Comment by folbricht** [comment]
@limbo127 If you're storing indexes of indexes like you're describing, then I imagine one thing you'd benefit is being able to extract files to stdout, and read indexes from stdin. If that was supported (it's not yet), in conjunction with the remote-index support would allow you to do things like this:
```
desync extract -s http://chunk.store/ http://index.store/indexfile.caibx - | desync mount-index -s http://chunk.store - /mnt/dir
```
The first command would extract the larger index to stdout, which would then be read as index file in the second. You wouldn't need any files on disk in that case.

**Comment by limbo127** [comment]
Yes it’s good idea, at this time we are using mc/curl to download them.

**Comment by charles-dyfis-net** [comment]
We *do* support the first part of that (extract to stdout) with `desync cat`.

**Comment by folbricht** [comment]
Remote indexes were implemented in https://github.com/folbricht/desync/pull/51. Supporting reading/writing of indexes from STDIN/STDOUT will we dealt with separately.
