### ISSUE TITLE
infinite loop ?

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#5]
Hello, 

image_one.raw is a 100Gb file contains data 

1 - desync make -n 16 -s /data/store one.index  image_one.raw
takes < 1h to finish , one.index is created, store contains chunks
( htop show 16 process during operation ) 

image_two.raw is a copie of image_one.raw with 1G modifications of data
2 - desync make -n 16 -s /data/store two.index image_two.raw
after 36H , the process is always running  ( htop show 3 process at 100% cpu) 
no two.index file, store has not changes.

-> I do not think is a normal behaviour 
-> how help ? debug mode ? 

Regards, 
Nicolas

go version 1.9.2 
linux 64bit, standard fedora 26 version 
kernel 4.14

**Comment by folbricht** [comment]
Unfortunately there's no debug-mode as such at the moment, it'd be quite noisy and concurrency will make it hard to read as well. It'd be perfect if there was a smaller image file that exhibits this behaviour and which I could get my hands on to debug the issue.

The file `two.index` does get actually created as a tempfile, probably called `.two.index12345` or similar so you should see that with `ls -la`. Take a look if that looks complete. My current guess is that the chunking completed fine, but then something is preventing a goroutine from completing which then blocks the tool from carrying on and renaming the tempfile. Going to try and reproduce it.

**Comment by charles-dyfis-net** [comment]
Reproducing with `GOTRACEBACK=all` exported in the environment, and terminating with `SIGABRT`, may also provide useful clues.

**Comment by limbo127** [comment]
no .two.xxxx 
i'm stopping the process and test with GOTRACEBACK=all
I notice that when i'm starting the command, i've got 16 process, as ( n -16) but few minutes after, there's a only 2.

**Comment by folbricht** [comment]
The `make` command has 3 distinct phases:

1. It reads the whole file and creates the index (in memory). On your HW, that should take no more than 5 min, likely less.
2. The index is then used to chunk the file, compress and store the chunks in the store. This step is very I/O intensive which can make this take a bit longer (about 1h in your case). 
3. Write the index to disk, this take almost no time at all, maybe a second.

You can see that any subsequent run with most of the chunks already in the store should take no more than a handful of minutes. From your description, perhaps it's phase 2 where the problem occurs.

I haven't been able to reproduce the issue on my side, even with a 100G file and several runs. If you can still see it hang after a few min and repro the issue, perhaps I'll make a version (on a branch) with additional logging to help us narrow it down a bit.

Also, please try the very latest version. I fixed a potential race condition around error handling. Don't think it's what you're running into but wouldn't hurt to try.

**Comment by limbo127** [comment]
export GOTRACEBACK=all
[root@retd wim]# /data2/gopath/bin/desync make  -s /data2/tmp/store_desync one.index /data2/tmp/windows_base.raw
SIGABRT: abort
PC=0x462f41 m=2 sigcode=0

goroutine 0 [idle]:
runtime.usleep(0x1e12400002710, 0x0, 0x1e11353bef2d4, 0x45d964b800, 0x2710690aee40, 0x1e124fa014d28, 0x45d964b800, 0x3e, 0x0, 0x1e11353bef2d4, ...)
        /usr/lib/golang/src/runtime/sys_linux_amd64.s:98 +0x41
runtime.sysmon()
        /usr/lib/golang/src/runtime/proc.go:3849 +0xa8
runtime.mstart1()
        /usr/lib/golang/src/runtime/proc.go:1182 +0x11e
runtime.mstart()
        /usr/lib/golang/src/runtime/proc.go:1152 +0x64

goroutine 1 [chan receive, 146 minutes]:
github.com/folbricht/desync.IndexFromFile(0xad36c0, 0xc42005e200, 0x7ffd6aefb68f, 0x1b, 0xa, 0x4000, 0x10000, 0x40000, 0x0, 0x0, ...)
        /data2/gopath/src/github.com/folbricht/desync/make.go:93 +0x9aa
main.makeCmd(0xad36c0, 0xc42005e200, 0xc4200100e0, 0x4, 0x4, 0x0, 0x0)
        /data2/gopath/src/github.com/folbricht/desync/cmd/desync/make.go:58 +0x408
main.main()
        /data2/gopath/src/github.com/folbricht/desync/cmd/desync/main.go:77 +0x6a8

goroutine 5 [syscall, 156 minutes]:
os/signal.signal_recv(0x0)
        /usr/lib/golang/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/lib/golang/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [select, 156 minutes, locked to thread]:
runtime.gopark(0x7747c8, 0x0, 0x75fb2f, 0x6, 0x18, 0x1)
        /usr/lib/golang/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc42003cf50, 0xc420078180)
        /usr/lib/golang/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
        /usr/lib/golang/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1

goroutine 7 [chan receive, 156 minutes]:
main.main.func2(0xc420010240, 0xc420044a40)
        /data2/gopath/src/github.com/folbricht/desync/cmd/desync/main.go:50 +0x34
created by main.main
        /data2/gopath/src/github.com/folbricht/desync/cmd/desync/main.go:49 +0x191

goroutine 53 [runnable]:
github.com/folbricht/desync.(*pChunker).syncWith(0xc4200945a0, 0xf9d9ee6f9409811c, 0x50fd944514bfee9, 0xb78c845e27b30fa5, 0xf233c5d846954b2f, 0xc80038c59, 0x40000, 0x0)
        /data2/gopath/src/github.com/folbricht/desync/make.go:182 +0x76
github.com/folbricht/desync.(*pChunker).start(0xc420094480, 0xad36c0, 0xc42005e200)
        /data2/gopath/src/github.com/folbricht/desync/make.go:165 +0x2e7
created by github.com/folbricht/desync.IndexFromFile
        /data2/gopath/src/github.com/folbricht/desync/make.go:84 +0x90e

rax    0xfffffffffffffffc
rbx    0x3e
rcx    0x462f41
rdx    0x0
rdi    0x0
rsi    0x0
rbp    0x7f99690aede0
rsp    0x7f99690aedd0
r8     0x7f99690aedd0
r9     0x0
r10    0x0
r11    0x246
r12    0x0
r13    0xf1
r14    0x11
r15    0x0
rip    0x462f41
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
[root@retd wim]#

**Comment by folbricht** [comment]
Thank you. Very useful. This means it's stuck in phase1, likely at the end of it where it should carry on. Unfortunately it's also the most complex piece of the parallel chunking algorithm and I'm going to need a bit of time to rewrite it/look for possible race-condition in that.

What sort of CPU do you have, like how many cores especially? Just wondering if your HW is more likely to trigger any races, since I can't reproduce it at all.

**Comment by limbo127** [comment]
two cpu : Intel(R) Xeon(R) CPU E5-2609 0 @ 2.40GHzU 
8 core each , *2 hyperthread => ~ 16 vcore
96g ram

**Comment by limbo127** [comment]
is it possible that the issues comes from image raw file ? : 
an other test : 
 desync make -n 16 -s /data/store_one  one.index image_one.raw
>> 15 minutes

( other image, other store , image_two.raw is the image used during the first test, same store)
desync make -n 16 -s /data/store_two two.index image_two.raw

=> never finish

**Comment by folbricht** [comment]
It's certainly conceivable that it's triggered by a specific file and the way it's chunked. I did identify an issue that would cause it to hang if the chunker algorithm encounters an error - for example while reading the file - it wouldn't handle the error and stop in this case. I will have a fix for this in a few hours. If you did run into that, it would mean there's an error during the chunking so perhaps it's not the same issue.

If that doesn't help, I'll make a special build with extra logging for you. Please keep `image_two.raw` around to test the fix and repro.

**Comment by folbricht** [comment]
@limbo127 There's now a fix for the error handling on master. If the tool still hangs after updating, please try a build from https://github.com/folbricht/desync/tree/issue-5-debug which will print debug messages to stdout. The extra debugging should allow me to narrow it down a bit if it does hang in phase 1 of the chunking algorithm.

**Comment by limbo127** [comment]
test on master branch does not change anything.
I cannot get debug ouput from issue-5-debug 
cd $GOPATH/src/github.com/folbricht/desync
git checkout issue-5-debug
go clean
go build -v github.com/folbricht/desync/cmd/desync
go install github.com/folbricht/desync/cmd/desync

**Comment by folbricht** [comment]
Sorry, my bad, pushed branch, but not the the debug code. It's there now and should look something like this:

```
cd github.com/folbricht/desync/cmd/desync
git co issue-5-debug
go build
./desync make -s store/ image.idx image.raw
2018/01/23 14:31:56 worker0 - starting at pos 0
2018/01/23 14:31:56 worker1 - starting at pos 1048576
2018/01/23 14:31:56 worker2 - starting at pos 2097152
2018/01/23 14:31:56 worker3 - starting at pos 3145728
2018/01/23 14:31:56 worker4 - starting at pos 4194304
2018/01/23 14:31:56 worker5 - starting at pos 5242880
2018/01/23 14:31:56 worker6 - starting at pos 6291456
2018/01/23 14:31:56 worker7 - starting at pos 7340032
2018/01/23 14:31:56 worker8 - starting at pos 8388608
2018/01/23 14:31:56 worker9 - starting at pos 9437184
2018/01/23 14:31:56 worker9 stopping
2018/01/23 14:31:56 worker0 found sync with worker1 at pos 1147563
2018/01/23 14:31:56 worker0 stopping
2018/01/23 14:31:56 assembler read 16 chunks from worker0
2018/01/23 14:31:56 worker1 found sync with worker2 at pos 2488945
2018/01/23 14:31:56 worker1 stopping
2018/01/23 14:31:56 assembler read 23 chunks from worker1
2018/01/23 14:31:56 worker2 found sync with worker3 at pos 3243482
2018/01/23 14:31:56 worker2 stopping
2018/01/23 14:31:56 assembler read 10 chunks from worker2
2018/01/23 14:31:56 worker3 found sync with worker4 at pos 4278711
2018/01/23 14:31:56 worker3 stopping
2018/01/23 14:31:56 assembler read 16 chunks from worker3
2018/01/23 14:31:56 worker4 found sync with worker5 at pos 5315863
2018/01/23 14:31:56 worker4 stopping
2018/01/23 14:31:56 assembler read 20 chunks from worker4
2018/01/23 14:31:56 worker5 found sync with worker6 at pos 6375204
2018/01/23 14:31:56 worker5 stopping
2018/01/23 14:31:56 assembler read 16 chunks from worker5
2018/01/23 14:31:56 worker6 found sync with worker7 at pos 7393606
2018/01/23 14:31:56 worker6 stopping
2018/01/23 14:31:56 assembler read 19 chunks from worker6
2018/01/23 14:31:56 worker7 found sync with worker8 at pos 8409079
2018/01/23 14:31:56 worker7 stopping
2018/01/23 14:31:56 assembler read 17 chunks from worker7
2018/01/23 14:31:56 worker8 found sync with worker9 at pos 9488483
2018/01/23 14:31:56 worker8 stopping
2018/01/23 14:31:56 assembler read 13 chunks from worker8
2018/01/23 14:31:56 assembler read 15 chunks from worker9
2018/01/23 14:31:56 worker9 reached eof - chunking complete
````

**Comment by limbo127** [comment]
hello, 
the process seems to be blocked ( waiting for 40 min, takes 16mins with the other image) 
[root@retd dev]# time /tmp/desync make -n 16 -s /data/nicolas/dev/store_1  3.index /data2/tmp/windows_base.raw 
2018/01/23 17:24:31 worker0 - starting at pos 0
2018/01/23 17:24:32 worker1 - starting at pos 6710886400
2018/01/23 17:24:32 worker2 - starting at pos 13421772800
2018/01/23 17:24:32 worker3 - starting at pos 20132659200
2018/01/23 17:24:32 worker4 - starting at pos 26843545600
2018/01/23 17:24:32 worker5 - starting at pos 33554432000
2018/01/23 17:24:32 worker6 - starting at pos 40265318400
2018/01/23 17:24:32 worker7 - starting at pos 46976204800
2018/01/23 17:24:32 worker8 - starting at pos 53687091200
2018/01/23 17:24:32 worker9 - starting at pos 60397977600
2018/01/23 17:24:32 worker10 - starting at pos 67108864000
2018/01/23 17:24:32 worker11 - starting at pos 73819750400
2018/01/23 17:24:32 worker12 - starting at pos 80530636800
2018/01/23 17:24:32 worker13 - starting at pos 87241523200
2018/01/23 17:24:32 worker14 - starting at pos 93952409600
2018/01/23 17:24:32 worker15 - starting at pos 100663296000
2018/01/23 17:26:30 worker6 found sync with worker7 at pos 46976204800
2018/01/23 17:26:30 worker6 stopping
2018/01/23 17:26:30 worker4 found sync with worker5 at pos 33554432000
2018/01/23 17:26:30 worker4 stopping
2018/01/23 17:34:02 worker15 stopping
2018/01/23 17:34:03 worker11 found sync with worker12 at pos 80530636800
2018/01/23 17:34:03 worker11 stopping
2018/01/23 17:34:05 worker9 found sync with worker10 at pos 67108864000
2018/01/23 17:34:05 worker9 stopping
2018/01/23 17:34:05 worker12 found sync with worker13 at pos 87241523200
2018/01/23 17:34:05 worker12 stopping
2018/01/23 17:34:05 worker7 found sync with worker8 at pos 53687091200
2018/01/23 17:34:05 worker7 stopping
2018/01/23 17:34:05 worker13 found sync with worker14 at pos 93952409600
2018/01/23 17:34:05 worker13 stopping
2018/01/23 17:34:05 worker14 found sync with worker15 at pos 100663296000
2018/01/23 17:34:05 worker14 stopping
2018/01/23 17:34:06 worker10 found sync with worker11 at pos 73819750400
2018/01/23 17:34:06 worker10 stopping
2018/01/23 17:34:06 worker8 found sync with worker9 at pos 60397977600
2018/01/23 17:34:06 worker8 stopping
2018/01/23 17:34:21 worker1 found sync with worker2 at pos 13421828123
2018/01/23 17:34:21 worker1 stopping
2018/01/23 17:34:21 worker2 found sync with worker3 at pos 20132682217
2018/01/23 17:34:21 worker2 stopping
2018/01/23 17:34:23 worker0 found sync with worker1 at pos 6711115836
2018/01/23 17:34:23 worker0 stopping
2018/01/23 17:34:23 assembler read 89675 chunks from worker0
2018/01/23 17:34:23 assembler read 86005 chunks from worker1
2018/01/23 17:34:23 assembler read 90811 chunks from worker2
f

**Comment by charles-dyfis-net** [comment]
...so as I read this, 4 syncs with 5 and shuts down *before* 3 syncs with 4. What needs to happen there is that 3 needs to try to sync with 5 if it runs out of chunks from 4, but it looks to me like that isn't actually happening.

I wonder if maybe the input file might have large all-zero swaths in it, by the way? That kind of region (with no boundary points to cause the threads to align) would make sense in terms of triggering this bug.

If you need something to use right now, btw, older versions of desync didn't do parallel chunking -- they're slower, but still faster than casync, and using one in the interim will be a workaround for the issue at hand.

**Comment by limbo127** [comment]
with no // , it's working
[root@retd dev]# time /tmp/desync make -n 1 -s /data/nicolas/dev/store_1  3.index /data2/tmp/windows_base.raw 
2018/01/23 18:04:26 worker0 - starting at pos 0
2018/01/23 18:33:42 worker0 stopping
2018/01/23 18:33:42 assembler read 635933 chunks from worker0
2018/01/23 18:33:42 worker0 reached eof - chunking complete

**Comment by limbo127** [comment]
and yes, the raw image à 85% of zero. 
nicolas

**Comment by folbricht** [comment]
@limbo127 Good news. I was able to reproduce the issue and yes, it was a bug related to having large sections of the input file contain only 0-bytes. It's fixed now, on master as well as the debug branch.

Also implemented an optimization suggested by @charles-dyfis-net that should make chunking in your use case more efficient and perhaps a bit faster.

Thanks for your patience. Let me know if it works for your now.

**Comment by limbo127** [comment]
hello it's working with latest master commit, but , chunk of img2.raw ( the image that do not work before) is very long time compare to the other.

[root@retd dev]# time /data2/gopath/bin/desync make -n 16 -s /data/nicolas/dev/store_2  2.index /data2/tmp/img1.raw 

real    17m53.684s
user    34m58.898s
sys     2m47.639s

[root@retd dev]# time /data2/gopath/bin/desync make -n 16 -s /data/nicolas/dev/store_1  1.index /data2/tmp/img2.raw 

real    34m9.690s
user    54m56.970s
sys     3m16.293s

**Comment by folbricht** [comment]
That can happen if there's a very large patch of zeroes in the middle of the file, then the chunker can't work effectively in parallel. I suspect that the more real data gets put into the image, and the more evenly it's spread out, the faster chunking will be.

If you run the latest debug version, and paste the output, it'll tell us where in your file it encounters the large blank space and has to work extra hard. It'll say something about "skipping workers". Worst case even though you have 16 workers with -n 16, some of those won't be able to contribute to the chunking process.

**Comment by limbo127** [comment]
it's ok for me, 0 is not real data .
