### ISSUE TITLE
Support uncompressed chunk stores

### ISSUE THREAD

**Issue by folbricht** [folbricht/desync#50]
Storing chunks uncompressed can reduce latency and improve performance in some use-cases, such as when using FUSE mounts and local caches. Upstream casync stores uncompressed chunks without the `.cacnk` extension which avoids collisions with compressed chunks in the same store.

- HTTP, local, S3 and SFTP stores should support reading/writing uncompressed chunks (SSH may be added later)
- There needs to be some config to tell the tool which store is compressed vs uncompressed when dealing with multiples. Likely have to add that to the config file to avoid overloading the commandline
- The `chunk-server` command needs to be able to serve/store uncompressed chunks as well

**Comment by charles-dyfis-net** [comment]
When reading from a store, I'm not sure we need to have a compression flag configured -- try both, with the mechanism we used for the last chunk we found checked first to reduce the number of extra syscalls, and there we are. It's only writes that definitely need configuration.

**Comment by folbricht** [comment]
An early implementation of this is available on a branch now (https://github.com/folbricht/desync/tree/issue-50). Uncompressed chunks are now stored without `.cacnk` extension, and both kinds of chunks can be stored in the same chunkstore. However, one client accesses the chunkstore in one way only. There is no automatic detection of type since that could lead to unexpected side-effects (multiple clients can access the same stores in different formats though).

When reading chunks from multiple stores and caches, it's possible to configure some as uncompressed and leaving the others compressed. This may be useful for local caches. To configure everything to run uncompressed for best performance:
- On the client, create a .config/desync/desync.json config file, specifying the stores it reads from and setting those to `"uncompressed": true`. Examples are provided in the Readme
- If one of the stores is a `chunk-server` it needs to be executed with `-u` to only server uncompressed chunks. It'll not allow queries for compressed ones and fail with 400
- On the chunk-server, all upstream chunkstores, in most use-cases should be set to decompressed as well. If that's not done, the chunk-server will have to decompress every chunk requested (though there may be situations where this is desirable with a fat server and thin clients).

There are other improvements as a result of this change, like chunks are now validated much earlier in the process, avoiding invalid chunks making it into local caches. Also it's now possible to configure options for each store independently in the config file.

TODO:
- Better document compressed/uncompressed chunk stores in Readme
- Allow the config file to be specified in the command line
