### ISSUE TITLE
Modify tags to comply with semantic versioning for go module support

### ISSUE THREAD

**Issue by charles-dyfis-net** [folbricht/desync#57]
The [Go module mechanism introduced with 0.11](https://github.com/golang/go/wiki/Modules) expects tags to be named with the form `v<major>.<minor>.<point>` (and adds requirements that module names for any major number >=2 include "v<major>").

At present, tags are of the form `release-0.1`, `release-0.2` and `release-0.3`. I propose creating `v0.1.0`, `v0.2.0` and `v0.3.0` tags matching them.

**Comment by folbricht** [comment]
Done. https://github.com/folbricht/desync/releases
