### ISSUE TITLE
Allow equivalence in json configuration file

### ISSUE THREAD

**Issue by SebastienAuvray** [folbricht/desync#66]
As of #62, I'm using a json config file to declare uncompressed stores. The declaration in this file and the use in desync functions must be exactly the same, which can lead to mistakes. 

The following declarations :
 {"store-options": {"http://localhost:9001":{"uncompressed": true}}}
 {"store-options": {"/home/me/store/":{"uncompressed": true}}}
are not properly taken into account when I use the following declarations :
-s http://localhost:9001/  # leading "/"
-s /home/me/sore # No leading "/"

Could you "interpret" these parameter instead of testing their equality with the cache paths/URLs ?

**Comment by folbricht** [comment]
Not as straightforward as it seems, but should be doable. Will need to consider the following kinds of store locations:

- URLs, should be easy to compare once the path is cleaned up
- relative Unix paths, need to compare to absolute ones
- absolute Unix paths
- relative Windows paths, this could be the most tricky one
- absolute Windows paths

The code to parse locations could do with a cleanup anyway so perhaps that could be combined with this request.

**Comment by folbricht** [comment]
Addressed in https://github.com/folbricht/desync/pull/67
