### ISSUE TITLE
Info output : stdout vs. stderr

### ISSUE THREAD

**Issue by SebastienAuvray** [folbricht/desync#68]
"desync info" outputs plain text format to stdout but json format to stderr ; could you output both to stdout ?

**Comment by folbricht** [comment]
Doable. The reason it's going to STDERR is that some commands like `extract` can write data to STDOUT which would conflict with the JSON stats they can produce as well. But for the info command, there's no such limitation.

**Comment by SebastienAuvray** [comment]
Thank you.

**Comment by folbricht** [comment]
Done in https://github.com/folbricht/desync/commit/8737a7321e6426e100cfa698111d8b2bdd4caeab
