### ISSUE TITLE
Fix main package tests on Windows

### ISSUE THREAD

**Issue by folbricht** [folbricht/desync#72]
Several of the command tests in the main package currently fail when run on Windows. They all appear to be related to the OS, not functional failures. Things like error messages being different, and some issues with finding the user profile.

**Comment by akhilpathania** [comment]
Hello,
Can you please guide me for installing desync in windows golang.
I am using go get url-of-desync but it is returning gcc executable bot found.

**Comment by folbricht** [comment]
gcc is needed to compile zstd which is a dependency. Last time I tried it I used installing Mingw-w64 which will give you gcc on Windows (http://mingw-w64.org/), then add that to your path and it should build.

**Comment by akhilpathania** [comment]
I am trying to make chunks of  a directory in windows, how should i do it.
