### ISSUE TITLE
Error: failed to retrieve chunk <chunk id>: open <path-to-chunk-on-fs> too many open files

### ISSUE THREAD

**Issue by codingonHP** [folbricht/desync#74]
## Steps to reproduce:
1. Create and server a fs based index and chunk store.
2. Make (n > 1024) concurrent requests to download chunks based on index
3. Errors will be printed on stdout

Default resource limit for file descriptors on linux systems is 1024.
How do I solve this issue?

### Proposed Solution
Introduce cached fs store.

**Comment by folbricht** [comment]
The typical solution would be to increase the limit on the server with `ulimit`. Keep in mind that not only reading the chunk files from disk will use a file descriptor but also the network sockets.

Can you elaborate on your proposed solution? desync currently has local stores that can be used as caches, but that would still involve file handles.

**Comment by codingonHP** [comment]
Thanks for the help. Yeah increasing the `ulimit` does the trick. Also, I can use caches (maybe, I have not yet tried it). It's the same thing I was trying to propose (should have paid attention to README :/ )
