### ISSUE TITLE
enhancement : add xattrs support

### ISSUE THREAD

**Issue by kmeaw** [folbricht/desync#83]
Currently desync does not support extended attributes.
Extended attributes support is needed to use desync as a root filesystem imaging tool.

**Comment by kmeaw** [comment]
This issue could be worked around by imaging the filesystem into a regular .tar file and running (describe-tar)[https://github.com/kmeaw/describe-tar] -xattrs on it to have a list of "special" files to restore later.

**Comment by folbricht** [comment]
xattrs support actually exists in casync/catar files https://github.com/systemd/casync/blob/e4a3c5efc8f11e0e99f8cc97bd417665d92b40a9/src/caformat.h#L54 but at the time I wanted to keep things simple in desync and didn't need it. It's a nice thing to have though. Is that something you want to try implementing yourself? Or perhaps we can do that together on a feature branch if you like.

The format encoder in desync already has partial support for it, see: https://github.com/folbricht/desync/blob/master/format.go#L481 though it's not used by `tar` yet.
