### ISSUE TITLE
enhancement : output cache progress bar as parsable 

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#86]
Hello, 
can you create an option to give a parsable progress bar in desync cache command , example, only percentage in stdout or json 

Regards, 
Nicolas Prochazka

**Comment by folbricht** [comment]
I don't really see a good way to implement this cleanly. desync currently uses https://github.com/cheggaaa/pb for the progress bar for that. Maybe it can be configured to always show the percentage, but apart from that I don't have any ideas.

Do you have any suggestions/examples of what that could look like?

**Comment by limbo127** [comment]
Hello, 
- the first issue is that cheggaaa/pb  cannot redirect into file or stdout / stderr 
- as desync cache can be very long in our case, we only need an information about progression  , than can be redirect into file or std* .
Regards, 
Nicolas

**Comment by folbricht** [comment]
The progress bar is already written to stderr currently, but that only happens if it runs in a terminal as you can see here https://github.com/folbricht/desync/blob/master/cmd/desync/progressbar.go#L14-L20

If there was a way to force it to show the progress bar even on non-terminals (perhaps via env variable), would that be enough for you to parse it?

**Comment by limbo127** [comment]
Hello,
Our tests show that even in a terminal we do not manage to recover the
progress bar (2> & 1 | )
and yes we can parse currently progress bar

Nicolas

**Comment by folbricht** [comment]
@limbo127 Please take a look at https://github.com/folbricht/desync/pull/90 when you have a moment. Perhaps that will allow you to track progress. It's quite a crude solution, but maybe it allows you to do what you're planning.

**Comment by limbo127** [comment]
hello, 
perfect for us
Nicolas
