### ISSUE TITLE
Add support for S3 stores

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#9]
Hello, 
when desync creates a chunk, it creates a tempfile, then move it to real name. 
Using desync with aws S3 object store is not very efficient, because of move does not exist in s3 ( copy + delete) . Can you suppress tmp creation process or optional it ?  
Regards, 
Nicolas Prochazka

**Comment by charles-dyfis-net** [comment]
This would be exactly the wrong behavior on POSIX-compliant filesystems, where the create+rename is the standardized way to create a file atomically.

What layer are you using to expose S3 as a filesystems? Giving that tool the ability to avoid creating hidden files would not only fix its behavior as a backend for desync, but also casync, sed -i, and numerous other tools.

**Comment by limbo127** [comment]
Rsync --inplace option is from client side operation. 
we are using https://github.com/kahing/goofys to mount s3 bucket.
Regards, 
Nicolas Prochazka

**Comment by charles-dyfis-net** [comment]
@limbo127, ...per the linked goofys ticket -- said project's maintainer takes the position that large numbers of small files is an inherently suboptimal use. And frankly, I'm not willing to add new codepaths that will only be relevant to users of a niche filesystem and harmful to everyone else.

If you were to propose a patch to desync giving it direct S3 support (just as it currently has direct SSH and HTTP support), I'd be happy to review it -- that would be more efficient than the extra FUSE layer, and avoid the server-side rename problem.

**Comment by folbricht** [comment]
Direct S3 support in desync seems to be the cleanest solution, and I imagine this could be very useful to others as well. Going to give this a try this or next weekend.

**Comment by limbo127** [comment]
ok thanks, 
please read about  https://github.com/kahing/goofys , there's a lot of tips about s3 api or https://github.com/minio/mc .
regards
nicolas

**Comment by folbricht** [comment]
My plan is to simply use https://github.com/minio/minio-go rather than implementing the client myself.

**Comment by folbricht** [comment]
The first implementation of S3 support can be found on the branch https://github.com/folbricht/desync/tree/s3-store While it seems functional, I'm having problems with minio's client library not (always) using http-keepalive and under load running out of sockets because of it. It could be something specific to my test setup. I'm still investigating.

**Comment by limbo127** [comment]
great !
I test it as soon as possible
nicolas

**Comment by limbo127** [comment]
[root@retd desync]# go build
# _/data2/gopath2/src/github.com/folbricht/desync/cmd/desync
./extract.go:135:48: cannot use chunks (type []desync.IndexChunk) as type desync.Index in argument to desync.AssembleFile

**Comment by folbricht** [comment]
Your repo seems to be inconsistent, so the library part must be updated while everything under cmd/desync is old. Your code should look like this https://github.com/folbricht/desync/blob/s3-store/cmd/desync/extract.go#L95

What I'd do is use git to ensure you're on the right code:
```
git fetch
git checkout s3-store
git pull
```

**Comment by limbo127** [comment]
ok, 
I do not understand new S3 format in your example.
how specify region ? bucket ? 
regards, 
nicolas

**Comment by folbricht** [comment]
At this point I don't have a way to specify region. In `s3+http://127.0.0.1:9000/store`, the bucket would be `store`.

Any suggestions of how we could provide the region in that format?

**Comment by folbricht** [comment]
Actually, isn't region usually encoded in the hostname like so `s3+http://myregion.host.name:9000/bucket`?

**Comment by limbo127** [comment]
region is used by authentifcation scheme
desync_s3 make -s s3+http://test.eu.neo.s3-eu-west-1.amazonaws.com
The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'

**Comment by folbricht** [comment]
I don't have an Amazon S3 account to test against, but from reading their description, I believe the URL would be like this in your case `s3+https://s3-eu-west-1.amazonaws.com/test`, assuming the bucket name is `test` and also note the `https` which will force it to use SSL.

There's a bit of magic around parsing Amazon URLs in the Minio client library which I don't fully understand yet.

**Comment by limbo127** [comment]
please give me a private email, i create you a bucket and access/secret key
regards

2018-02-19 20:23 GMT+01:00 folbricht <notifications@github.com>:

**Comment by folbricht** [comment]
Thank you, you can see my email address in my profile now.

**Comment by folbricht** [comment]
Minio client issue (with suggested solution) filed in https://github.com/minio/minio-go/issues/924

**Comment by folbricht** [comment]
Documentation has been updated, the correct way to specify a URL in AWS is this, with https and without port: `s3+https://s3-eu-west-3.amazonaws.com/desync.bucket`

**Comment by limbo127** [comment]
always get acced denied with make command
S3_ACCESS_KEY=x S3_SECRET_KEY=x /tmp/desync_s3 make -s s3+https://s3-eu-west-3.amazonaws.com/desync.bucket/ VERSION_VM.index VERSION_VM 
s3+https://s3-eu-west-3.amazonaws.com/desync.bucket/: Access Denied.

**Comment by folbricht** [comment]
You're almost there :) Remove the trailing `/` from the URL. What basically happens here is that the bucket name is the basename of the URL path. So if you have a trailing slash, the bucket name is empty.

I could perhaps change this and always use the first path element as bucket name and error when there's more than one. Having said that, https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html also doesn't use trailing `/` in their URLs.

**Comment by folbricht** [comment]
Prefixes are now supported as well, so this can be used to specify "directories" in the URL.

s3+https://s3-eu-west-3.amazonaws.com/desync.bucket/store

Note, the fix for the minio connection-pool issue has just been merged, so you may want to update that with `go get -u github.com/minio/minio-go`

**Comment by folbricht** [comment]
The s3-store branch has been merged to master.
