### ISSUE TITLE
enhancement : verify chunk exist from store

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#92]
Hello, 
Sometimes, our store lost chunk, due to bad manipulation or disk error.
In this case, we cannot continue to use desync cache command  on a lot of index file because of the "chunk missing error message" that's breaking process.  For us, it's normal behaviour.

Idea is to add a new command, that takes as parameter a indexFile or list of indexFile,  and a list of store ( -s ) , and verify that's all the chunks are available, if it's not the case, the index file is definitely not usable, so the  command can delete it. 

Regards, 
Nicolas Prochazka

**Comment by folbricht** [comment]
If I understand the goal correctly, this should be something that's scriptable using the `info` subcommand. Here's an example of what it looks like if the chunks are all present in the store. Note how `unique` and `in-store` match:
```
desync info -s testdata/blob1.store/ testdata/blob1.caibx 
{
  "total": 161,
  "unique": 131,
  "in-store": 131,
  "size": 2097152,
  "chunk-size-min": 2048,
  "chunk-size-avg": 8192,
  "chunk-size-max": 32768
}
```

And here's an example of what it looks like when you're missing chunks. The index references 131 `unique` chunks, but the store has only 124 `in-store` meaning there're several missing from the store.
```
desync info -s testdata/blob2.store/ testdata/blob1.caibx 
{
  "total": 161,
  "unique": 131,
  "in-store": 124,
  "size": 2097152,
  "chunk-size-min": 2048,
  "chunk-size-avg": 8192,
  "chunk-size-max": 32768
}
```
You can specify more than one store in the command line, and given that the output is JSON it should make it scriptable. Would that be an option for your use-case?

**Comment by limbo127** [comment]
Yes you are right,
Nicolas

Le mer. 16 janv. 2019 à 02:54, folbricht <notifications@github.com> a
écrit :
