### ISSUE TITLE
Error during desync make process

### ISSUE THREAD

**Issue by limbo127** [folbricht/desync#96]
Hello, 
sometimes, 
desync make -m  "64:256:512" -n 8  -s /data/store/ /data/cache2/indexes/index.index /data/image.raw

stop with this 
Error: /data/cache2/store: chunk id dde093ea6663c6907671b7ad7fa85fe225555d23dfc61a7083340a7d1b6a0e7b does not match its hash 0000000000000000000000000000000000000000000000000000000000000000

If I'm restart the command, it's working
Nicolas

**Comment by folbricht** [comment]
How long has this been happening? And how often does it happen? That part of the code hasn't changed in a while. Maybe I can put together a version with additional debugging for you.

**Comment by limbo127** [comment]
We are using a version from december. not very often, sometimes on big blob
( 60G )  , restart the same make on same blob works after, perhaps a
filesystem problem ?
regards,
Nicolas

Le lun. 11 févr. 2019 à 14:55, folbricht <notifications@github.com> a
écrit :

**Comment by folbricht** [comment]
I made a version which should print a little extra output when this happens. That may not be enough to figure out exactly what's happening, but help narrow it down. If you could run a build from https://github.com/folbricht/desync/tree/issue-96-debug until this reproduces that would be helpful. There should be no performance impact, and everything should run normally with that build.

Do you have any configuration for the local store you're chunking into? Like disabled compression?

**Comment by limbo127** [comment]
Ok for this debug version
And yes we are using uncompress mode in this local store
Regards,
Nicolas

Le mar. 12 févr. 2019 à 05:19, folbricht <notifications@github.com> a
écrit :

**Comment by limbo127** [comment]
Hello, not debug version but not only during make process
S3_ACCESS_KEY=$_awsAccessKeyWso S3_SECRET_KEY=$_awsSecretKeyWso desync cache -c s3+https://s3-eu-west-3.amazonaws.com/${_awsBucketStore}/clients/$_awsClientName/chunks/ -s ${_desyncStore} /data/cache2/indexes/$metadata.index
[=>--------------------------------------------------------------------------------------------------------------------------------------------------------]   1.09% 10s
Error: /data/cache2/store: chunk id 2c2b8b9e7bcc86ee862dbe534241898c0ce3052987ec14afc5596d9bfa9e3848 does not match its hash 0000000000000000000000000000000000000000000000000000000000000000

**Comment by folbricht** [comment]
In this example, was either or both of the stores uncompressed? Also was ${_desyncStore} a local store?

**Comment by limbo127** [comment]
sorry for the var.
In fact, this test is in  compressed mode . and desyncStore was local filesystem.
regards

**Comment by limbo127** [comment]
desync cache -c s3+
https://s3-eu-west-3.amazonaws.com/${_awsBucketStore}/clients/$_awsClientName/chunks/-s
${_desyncStore} /data/cache2/indexes/$metadata.index
[>------------------------------------------------------------------------------------------------------------------------------------------------------]
 0.66% 17m38sissue-96: failed to uncompress : no data in chunk
issue-96: failed to uncompress : no data in chunk
issue-96: failed to uncompress : no data in chunk
issue-96: failed to uncompress : no data in chunk
[>------------------------------------------------------------------------------------------------------------------------------------------------------]
 0.66% 18m02sissue-96: failed to uncompress : no data in chunk
[=>---------------------------------------------------------------------------------------------------------------------------------------------------------]
 0.66% 7s
Error: /data/cache2/store: chunk id
b439fbdb6a686f5312542b7a0e342c70df510d080564c39204868899d90b3119 does not
match its hash
0000000000000000000000000000000000000000000000000000000000000000





Le lun. 18 févr. 2019 à 15:27, folbricht <notifications@github.com> a
écrit :

**Comment by folbricht** [comment]
Thanks a lot for that. At least I now know which of the code-paths produces the error. I made another small update on the branch which will cause a panic in desync and print a stacktrace that should hopefully allow me to narrow it down further. Something seems to be reading empty chunks.

**Comment by limbo127** [comment]
no more reproductible
Nicolas
